### ISSUE TITLE
using cpu 

### ISSUE THREAD

**Issue by muhdlaziem** [tohinz/semantic-object-accuracy-for-generative-text-to-image-synthesis#11]
how do we use cpu for sampling or at least validating

**Comment by tohinz** [comment]
Hi, you can use cpu for sampling by following standard PyTorch procedure, i.e. not loading the model/data on the gpu. You can start by setting the `GPU_ID` in the test config file to -1. I'm not sure I checked for it properly though, so it might through some errors and point you to parts that are on the wrong device. Generally speaking, just remove all `.cuda()` from the code and set everything to `.to(device="cpu")` where necessary.

Running on CPU to sample a couple of images should be ok (I haven't tested how long this takes), but I assume it will be too slow to generate thousands of images to evaluate FID or something similar.

**Comment by tohinz** [comment]
Edit, as per the above fix this should hopefully be easy to do now (see `sample.sh`).
`...uses .to(device) instead of .cuda() for more device-agnostic code (works on CPU as well)...`
