### ISSUE TITLE
FID scores

### ISSUE THREAD

**Issue by rubencart** [tohinz/semantic-object-accuracy-for-generative-text-to-image-synthesis#16]
Hi, what software/code and parameters did you use to calculate the fid scores in your paper?

**Comment by tohinz** [comment]
Hi, we used the official implementation from [here](https://github.com/bioinf-jku/TTUR). We calculated the statistics of the validation set on 256x256 px resolution and used those statistics to calculate all results with generated images of 256x256 px resolution.

**Comment by rubencart** [comment]
Okay thanks!
