### ISSUE TITLE
Captions file structure

### ISSUE THREAD

**Issue by MariuszCS** [tohinz/semantic-object-accuracy-for-generative-text-to-image-synthesis#6]
Hi,

I believe that you have mistaken the labelxxx.pkl files structure. After the
with open(label_XX_XX.pkl, "rb") as f:
       captions = pickle.load(f)

captions is a list of lists i.e. [[29338, 0], [29338, 1], [29338, 2]...] and not list of dicts i.e. [{'image_id': XX, 'id': XX, 'idx': [XX, XX], 'caption': u'XX'}, ...], as you state.

**Comment by tohinz** [comment]
Hi, thanks for noticing this. I must have accidentally uploaded my old files, which only contain the indexes to the captions in the captions file.
I've just uploaded the correct caption files which should follow the described structure. Let me know if this works.

**Comment by MariuszCS** [comment]
Hi,

Now everything is ok ;)
