### ISSUE TITLE
Unclear how to sample from OP-GAN in response to custom captions

### ISSUE THREAD

**Issue by vinayprabhu** [tohinz/semantic-object-accuracy-for-generative-text-to-image-synthesis#7]
Hi!
It wasn't clear from the documentation as to how to sample from the OP-GAN  in response to custom captions in, say, a txt file.
Any help?

**Comment by tohinz** [comment]
Hi,

If you want to use arbitrary text to sample I would suggest you use the code provided in the AttnGAN Github. I use the same text encoder as the AttnGAN, so you should be able to use their model to get the text embeddings for arbitrary text to use with my model.

Check out this method (https://github.com/taoxugit/AttnGAN/blob/0d000e652b407e976cb88fab299e8566f3de8a37/code/main.py#L36) on how to prepare your sentence and then check out this (https://github.com/taoxugit/AttnGAN/blob/0d000e652b407e976cb88fab299e8566f3de8a37/code/trainer.py#L432) on how to use that to generate images.

For our model you'll also need bounding boxes as input (together with the caption embedding). You can create these yourself (in the form: [top left corner x in percent, top left corner y in percent, width in percent, height in percent], so e.g. [0,0,0.5,0.5] would be a bounding box covering the top left quarter of an image while [0.5,0.5,0.5,0.5] would cover the bottom right quarter of an image).

Alternatively, you can use a pretrained network to extract bounding boxes from a sentence as we did in the OP-GAN. We used the box generator from here: https://github.com/jamesli1618/Obj-GAN

**Comment by vinayprabhu** [comment]
I did the latter!
Thank you so very much for the detailed reply.
Best regards
